apiVersion: cs426.cloud/v1
kind: LoadgenResult
metadata:
  creationTimestamp: "2024-10-04T21:44:26Z"
  generation: 1
  name: bnq3-loadgen-1
  namespace: bnq3
  resourceVersion: "25292706"
  uid: 94275123-cdbe-49e2-a6f0-e9be13329f61
spec:
  average_latency_ms: 1005.4314
  duration_s: 60
  error_msg: ""
  errors: 0
  requests: 51
  stale_responses: 0